from datetime import datetime, timezone
from typing import Literal

from beanie import Document, PydanticObjectId
from pydantic import BaseModel, Field
from pymongo import IndexModel


class CircleMember(BaseModel):
    user_id: PydanticObjectId
    role: Literal["admin", "member"] = "member"
    joined_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class Circle(Document):
    name: str
    description: str = ""
    invite_code: str  # Unique 8-char alphanumeric, auto-generated by service
    created_by: PydanticObjectId
    members: list[CircleMember] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Settings:
        name = "circles"
        indexes = [
            IndexModel("invite_code", unique=True),
            IndexModel("members.user_id"),
        ]
